version: "3.9"
services:
  app:
    container_name: "rental-dvd"
    build: .
    working_dir: "/workspace"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    user: vscode
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data:
