//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3
pub extern crate chrono;
pub extern crate sea_orm;
pub extern crate uuid;

pub mod prelude;

#[cfg(feature = "server-side")]
pub mod db;

pub mod lists;
pub mod todos;
